### PR TITLE
Version check fix and renaming mindsdb -> mindsdb_native where needed

### LINKED ISSUE #42: Version check compares mindsdb_native to mindsdb (server)

### PR DESCRIPTION
**Pull request by btseytlin**
Resolves: https://github.com/mindsdb/mindsdb_native/issues/42

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -16,8 +16,8 @@ if [ "$mode" = "prod" ]; then
 fi
 
 if [ "$mode" = "dev" ]; then
-    pip3 uninstall mindsdb
-    pip3 uninstall mindsdb --user
+    pip3 uninstall mindsdb-native
+    pip3 uninstall mindsdb-native --user
     python3 setup.py develop --uninstall
```
Comment (George3d6) [inline install.sh]: Remove this file.

Also, I think it's `mindsdb_native` not `mindsdb-native`. But maybe both work, the former is how it's called on pip

File: README.md [hunk 2]
```diff
@@ -59,7 +59,7 @@ MindsDB is an Explainable AutoML framework for developers built on top of Pytorc
 * **Desktop**: You can use MindsDB on your own computer in under a minute, if you already have a python environment setup, just run the following command:
 
 ```bash
- pip install mindsdb --user
+ pip install mindsdb-native --user
```
Comment (George3d6) [inline README.md]: `_` instead of `-`

File: mindsdb_native/libs/helpers/general_helpers.py [hunk 3]
```diff
@@ -58,19 +52,19 @@ def check_for_updates():
...
-            log.warning(f'Got no response from update check server !')
-        log.warning(f'Could not check for updates, got excetpion {e} !')
+            log.warning(f'Got no response from update check server!')
+        log.warning(f'Could not check for updates, got excetpion: {e}!')
         return
 
     try:
-        if 'version' in ret and ret['version']!= __version__:
-            log.warning("There is a new version of MindsDB {version}, please upgrade using:\npip3 uninstall mindsdb --upgrade".format(version=ret['version']))
+        if 'version' in ret and ret['version'] != __version__:
```
Comment (George3d6) [inline mindsdb_native/libs/helpers/general_helpers.py:62]: Unless you modified the website at `http://check.mindsdb.com` this PR won't work, what you need to do is use the version of `mindsdb` not `mindsdb_native` here.

If there's no `mindsdb` installed just warn the user about something like `You are running on a machine with only mindsdb_native, a python library interface for Mindsdb, you might also wish to install the main mindsdb pip package`.

**Review by George3d6 — CHANGES_REQUESTED** [review]

File: mindsdb_native/libs/helpers/general_helpers.py (hunk 3 above)
Comment (btseytlin) [reply mindsdb_native/libs/helpers/general_helpers.py:62]: This will be solved on the side of the telemetry server:
https://github.com/mindsdb/mindsdb_server_enterprise/pull/2

**Comment by George3d6** [comment]
@btseytlin  looks fine, merging.
